### ISSUE TITLE
Docker support.

### ISSUE THREAD

**Issue by Tiritibambix** [Ilyas-Codes/eCourse#3]
Hello. Your project looks really interesting.
Is docker support in the works by any chance ?

**Comment by Ilyas-Codes** [comment]
Hey @tiritibambix thanks for checking out my project!
I can't guarantee you that since I'm not very familiar with Docker and I'm quite busy with work right now, though I'd be happy if you'd like to submit a PR for that.

**Comment by Tiritibambix** [comment]
I'd love to offer my help. Alas, all my attempts to learn Dockerfile have ended in abject failure 😅 I must confess I'm not the most computer-literate person in general ...
I hope someone else will be able to take this over :)
Take care.

**Comment by grenskul** [comment]
Made one .
The default pocketbase executable you're shipping is mac so I had to replace it .
Outside of that it's just following your prod build instructions
I  left it with port 80 and http cause I expect most people to put this behind a reverse proxy
I also deleted the contents  pb_data directory and deleted the client directory post build to save space

I built and pushed this to https://hub.docker.com/r/grenskul/ecourse but I'm probably not going to maintain this. It's a one off for a friend .
```
FROM node:20.11.0-buster
 
WORKDIR /

RUN git clone https://github.com/Ilyas-Codes/eCourse.git

WORKDIR /eCourse/client

RUN npm install 

RUN npm run build

RUN mv dist /eCourse/server/pb_public

RUN rm -r /eCourse/server/pb_data/*

RUN rm -r /eCourse/client

ADD pocketbase /eCourse/server/pocketbase

EXPOSE 80

CMD ["/eCourse/server/pocketbase", "serve", "--http=0.0.0.0:80"]

```

**Comment by Tiritibambix** [comment]
Oh that's awesome. Thanks you, it is working great :)

For anyone interested, here's the docker-compose I used:
```
version: '3.3'
services:
    ecourse:
        container_name: ecourse
        volumes:
            - '/path/to/eCourse/data:/eCourse/server/pb_data'
        ports:
            - '${PORT}:80'
        image: grenskul/ecourse
```

Can't the image creation be automated ? I believe I heard something about it.
